version: '3'

services:

  # Start cassandra and expose 9042
  charybdis-demo-scylla:
    container_name: charybdis-demo-scylla
    image: scylladb/scylla:latest
    ports:
      - "9042:9042"

  # Start the app on port 8080
  charybdis-demo-app:
    container_name: charybdis-demo-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - charybdis-demo-scylla
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    restart: always
